### ISSUE TITLE
raise ResolutionError( pkg_resources.ResolutionError: Script 'scripts/QuickWall' not found in metadata

### ISSUE THREAD

**Issue by Locvic** [deepjyoti30/QuickWall#15]
Hello, I am having an issue using QuickWall after installing using the following commands:

` git clone https://github.com/deepjyoti30/QuickWall`
`cd QuickWall`
`sudo python3 setup.py install`

Python version: 3.8.1
Distro: Void Linux

Running QuickWall only outputs this error:
```
➜  ~ QuickWall --search
Traceback (most recent call last):
  File "/usr/sbin/QuickWall", line 4, in <module>
    __import__('pkg_resources').run_script('QuickWall==0.0.2', 'QuickWall')
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/QuickWall' not found in metadata at '/home/vic/.local/lib/python3.8/site-packages/QuickWall-0.0.2.dist-info'
```

**Comment by deepjyoti30** [comment]
@victor31337 Can you give me the logs of installation. Seems like something went wrong while installing.

Also, did you try installing using ```pip```??

**Comment by Locvic** [comment]
```
➜  QuickWall git:(master) ✗ sudo pip install QuickWall
Collecting QuickWall
  Downloading https://files.pythonhosted.org/packages/f0/bc/f13b3be0254b9f4390b6070e8657604ddab5a11e083190d0d0431904cc21/QuickWall-0.0.2-py3-none-any.whl
Requirement already satisfied: pywal in /usr/lib/python3.8/site-packages (from QuickWall)
(3.3.0)
Requirement already satisfied: requests in /usr/lib/python3.8/site-packages/requests-2.22.0-py3.8.egg (from QuickWall) (2.22.0)
Requirement already satisfied: downloader-cli in /usr/lib/python3.8/site-packages/downloader_cli-0.1.0.post2-py3.8.egg (from QuickWall) (0.1.0.post2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages/certifi-2019.11.28-py3.8.egg (from requests->QuickWall) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.8/site-packages/chardet-3.0.4-py3.8.egg (from requests->QuickWall) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3.8/site-packages/idna-2.8-py3.8.egg (from requests->QuickWall) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages/urllib3-1.25.7-py3.8.egg (from requests->QuickWall) (1.25.7)
Installing collected packages: QuickWall
Successfully installed QuickWall-0.0.2
➜  QuickWall git:(master) ✗ QuickWall -h
/usr/bin/python3: can't open file '/usr/bin/QuickWall': [Errno 13] Permission denied
➜  QuickWall git:(master) ✗ sudo QuickWall -h
Traceback (most recent call last):
  File "/bin/QuickWall", line 14, in <module>
    from QuickWall.setter import WallSetter
  File "/usr/lib/python3.8/site-packages/QuickWall/setter.py", line 5, in <module>
    from QuickWall.kde import KDEsetpaper
  File "/usr/lib/python3.8/site-packages/QuickWall/kde.py", line 3, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```
This is what results after trying to install via pip

**Comment by deepjyoti30** [comment]
You need to have ```dbus``` installed.

Install it using ```sudo pip install dbus```

I forgot to add dbus as requirement to the setup.py

**Comment by Locvic** [comment]
`sudo pip3 install dbus` returns:
```
ERROR: Could not find a version that satisfies the requirement dbus (from versions: none)
ERROR: No matching distribution found for dbus
```
however, `sudo xbps-install -S python3-dbus` is successful.
but when running QuickWall this happens:
```
➜  ~ QuickWall --help
zsh: permission denied: QuickWall
```
running as sudo just returns the same error, I also tried changing permissions for the QuickWall binary but it just returns the same error:
```
➜  ~ sudo QuickWall
Traceback (most recent call last):
  File "/bin/QuickWall", line 4, in <module>
    __import__('pkg_resources').run_script('QuickWall==0.0.2', 'QuickWall')
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/QuickWall' not found in metadata at '/root/.local/lib/python3.8/site-packages/QuickWall-0.0.2.dist-info'
```

**Comment by deepjyoti30** [comment]
@victor31337 Was it fixed in the latest update? The package name was `dbus-python`

**Comment by Locvic** [comment]
I'm unable to replicate the error, I have moved on from Linux for now.
