### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'nitrogen'

### ISSUE THREAD

**Issue by G-R-A-F-F** [deepjyoti30/QuickWall#18]
Hi,
I am on XFCE image from xubuntu.org 
Not running nitrogen.
Getting this error when run QuickWall without any parameters:
```
3 MB   | 2   Mb/s || ETA: 0 s                                                                                                                                                                  |----------------------------------------| 100%Traceback (most recent call last):
  File "/home/graff/.local/bin/QuickWall", line 96, in <module>
    main()
  File "/home/graff/.local/bin/QuickWall", line 91, in main
    set_paper.do()
  File "/home/graff/.local/lib/python3.8/site-packages/QuickWall/SetPaper.py", line 107, in do
    self._set()
  File "/home/graff/.local/lib/python3.8/site-packages/QuickWall/SetPaper.py", line 68, in _set
    self.setter_type.set(self._file_path)
  File "/home/graff/.local/lib/python3.8/site-packages/QuickWall/nitrogen.py", line 28, in set
    p = subprocess.Popen(c.split(' '), stdout=subprocess.PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nitrogen'
```

OS:
```
OS: Ubuntu 20.04.1 LTS x86_64 
Kernel: 5.4.0-59-generic 
Uptime: 2 days, 14 hours, 27 mins 
Packages: 2535 (dpkg), 27 (flatpak), 18 (snap) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: Xfce 
WM: Xfwm4 
WM Theme: Xfce-Simple-Dark 
Theme: Xfce-Simple-Dark [GTK2], Greybird [GTK3] 
Icons: elementary-xfce-darker [GTK2/3] 
```

**Comment by deepjyoti30** [comment]
Hey @G-R-A-F-F Can you try passing the flag `--setter xfce`. It should work that way. By default it tries to use `nitrogen` which in your case won't be installed.

**Comment by G-R-A-F-F** [comment]
$ QuickWall --setter xfce
```
0 /backdrop/screen0/monitor0/workspace0/last-image
1 /backdrop/screen0/monitor0/workspace1/last-image
2 /backdrop/screen0/monitor0/workspace2/last-image
3 /backdrop/screen0/monitor0/workspace3/last-image
4 /backdrop/screen0/monitor0/workspace4/last-image
5 /backdrop/screen0/monitor0/workspace5/last-image
6 /backdrop/screen0/monitor0/workspace6/last-image
7 /backdrop/screen0/monitor0/workspace7/last-image
8 /backdrop/screen0/monitor0/workspace8/last-image
9 /backdrop/screen0/monitor0/workspace9/last-image
10 /backdrop/screen0/monitor0/workspace10/last-image
11 /backdrop/screen0/monitor0/workspace11/last-image
12 /backdrop/screen0/monitor0/workspace12/last-image
13 /backdrop/screen0/monitor0/workspace13/last-image
14 /backdrop/screen0/monitor0/workspace14/last-image
15 /backdrop/screen0/monitor0/workspace15/last-image
16 /backdrop/screen0/monitor0/workspace16/last-image
17 /backdrop/screen0/monitorDVI-0/workspace0/last-image
18 /backdrop/screen0/monitorDVI-0/workspace1/last-image
19 /backdrop/screen0/monitorDVI-0/workspace2/last-image
20 /backdrop/screen0/monitorDVI-0/workspace3/last-image
Which backdrop do you want to change?
```
passing 0 only changed color acent of my terminal background.

**Comment by gleba** [comment]
witch Pop!_OS same problem.

```
[Setter] Using xfce as wallpaper setter 
[Setter] --set-lockscreen not available for the current wallpaper setter 
[XFCE] /root/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml: Not found. Wallpaper will not be restored! 
[main] Getting the wallpapers using Unsplash API... 
[SetPaper] Saving images to /root/.cache/QuickWall 
[SetPaper] person using black laptop computer by XPS 
[XFCE] /root/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml: Not found. Assuming default monitor! 
Property "/backdrop/screen0/monitor0/workspace0/last-image" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.
ERROR:root:Imagemagick wasn't found on your system.
ERROR:root:Try another backend. (wal --backend)
```

**Comment by G-R-A-F-F** [comment]
> witch Pop!_OS same problem.
> 
> ```
> [Setter] Using xfce as wallpaper setter 
> [Setter] --set-lockscreen not available for the current wallpaper setter 
> [XFCE] /root/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml: Not found. Wallpaper will not be restored! 
> [main] Getting the wallpapers using Unsplash API... 
> [SetPaper] Saving images to /root/.cache/QuickWall 
> [SetPaper] person using black laptop computer by XPS 
> [XFCE] /root/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml: Not found. Assuming default monitor! 
> Property "/backdrop/screen0/monitor0/workspace0/last-image" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.
> ERROR:root:Imagemagick wasn't found on your system.
> ERROR:root:Try another backend. (wal --backend)
> ```

gleba, It looks like you are missing Imagemagic install.
