### ISSUE TITLE
Unable to start QuickWall

### ISSUE THREAD

**Issue by sauerj** [deepjyoti30/QuickWall#3]
Hey, thanks for your nice looking project!

I wanted to try it and installed QuickWall with `pip3 install QuickWall` on a Debian 9 Maschine.  
Current Python3 Version is 3.5.3.

This error appears on the first run of `QuickWall`:
```
Traceback (most recent call last):
  File "/home/jens/.local/bin/QuickWall", line 7, in <module>
    from QuickWall.SetPaper import SetPaper
  File "/home/jens/.local/lib/python3.5/site-packages/QuickWall/SetPaper.py", line 8, in <module>
    from QuickWall.blacklist import Blacklist
  File "/home/jens/.local/lib/python3.5/site-packages/QuickWall/blacklist.py", line 8, in <module>
    logger = Logger("blacklist")
  File "/home/jens/.local/lib/python3.5/site-packages/QuickWall/logger.py", line 17, in __init__
    self._check_logfile()
  File "/home/jens/.local/lib/python3.5/site-packages/QuickWall/logger.py", line 34, in _check_logfile
    os.makedirs(self._log_file.parent)
  File "/usr/lib/python3.5/os.py", line 226, in makedirs
    head, tail = path.split(name)
  File "/usr/lib/python3.5/posixpath.py", line 103, in split
    i = p.rfind(sep) + 1
AttributeError: 'PosixPath' object has no attribute 'rfind'
```

When I manually create `~/.QuickWall/logs` the following error occours:

```
Traceback (most recent call last):
  File "/home/jens/.local/bin/QuickWall", line 7, in <module>
    from QuickWall.SetPaper import SetPaper
  File "/home/jens/.local/lib/python3.5/site-packages/QuickWall/SetPaper.py", line 8, in <module>
    from QuickWall.blacklist import Blacklist
  File "/home/jens/.local/lib/python3.5/site-packages/QuickWall/blacklist.py", line 8, in <module>
    logger = Logger("blacklist")
  File "/home/jens/.local/lib/python3.5/site-packages/QuickWall/logger.py", line 17, in __init__
    self._check_logfile()
  File "/home/jens/.local/lib/python3.5/site-packages/QuickWall/logger.py", line 35, in _check_logfile
    f = open(self._log_file, 'w')
TypeError: invalid file: PosixPath('/home/jens/.QuickWall/logs/log.cat')
```

The path `~/.QuickWall/logs` is valid and writable.

Please contact me if you need more information.

**Comment by deepjyoti30** [comment]
I really think it is because of Python 3.5, can you try with later versions of Python. If you can confirm its a version specific issues, I'll bump up the requirements to python 3.6

**Comment by sauerj** [comment]
Retried in a Debian 10 VM with Python 3.7.3 and QuickWall works. Seems like Python 3.6 is a requirement.

**Comment by deepjyoti30** [comment]
Fixed in [#95d9ea](https://github.com/deepjyoti30/QuickWall/commit/95d9ea5b988ee69c03ccb83acd7472d114acc6a8)
